// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHV1bcUml28tQdP17y12-jtJIGwMqjuLM',
    appId: '1:740617122320:web:d9ae28d5365c03a6bfd095',
    messagingSenderId: '740617122320',
    projectId: 'projecttubesapb',
    authDomain: 'projecttubesapb.firebaseapp.com',
    databaseURL: 'https://projecttubesapb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projecttubesapb.firebasestorage.app',
    measurementId: 'G-7GW1JE4JJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvW8gbux9sjV57ocWErZam52h2-x5SSCk',
    appId: '1:740617122320:android:bf86d2c0601b3085bfd095',
    messagingSenderId: '740617122320',
    projectId: 'projecttubesapb',
    databaseURL: 'https://projecttubesapb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projecttubesapb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdaSa4CteMHDB3WHdTKDjWFSNhOfmToXk',
    appId: '1:740617122320:ios:2722e5fee0510e2cbfd095',
    messagingSenderId: '740617122320',
    projectId: 'projecttubesapb',
    databaseURL: 'https://projecttubesapb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projecttubesapb.firebasestorage.app',
    iosBundleId: 'com.example.projectTubesApb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdaSa4CteMHDB3WHdTKDjWFSNhOfmToXk',
    appId: '1:740617122320:ios:2722e5fee0510e2cbfd095',
    messagingSenderId: '740617122320',
    projectId: 'projecttubesapb',
    databaseURL: 'https://projecttubesapb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projecttubesapb.firebasestorage.app',
    iosBundleId: 'com.example.projectTubesApb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHV1bcUml28tQdP17y12-jtJIGwMqjuLM',
    appId: '1:740617122320:web:df7116eecff8543dbfd095',
    messagingSenderId: '740617122320',
    projectId: 'projecttubesapb',
    authDomain: 'projecttubesapb.firebaseapp.com',
    databaseURL: 'https://projecttubesapb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projecttubesapb.firebasestorage.app',
    measurementId: 'G-XFR6LS20Z0',
  );
}
